[package]
name = "markrust"
version = "0.1.0"
authors = ["guppy0130 <guppy0130@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.7"
