[package]
name = "markrust"
version = "1.1.0"
authors = ["guppy0130 <guppy0130@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = { version = "0.7.2", default-features = false, features = ["simd"] }
clap = "2.33.3"
