[package]
name = "markrust"
version = "1.5.0"
authors = ["guppy0130 <guppy0130@yahoo.com>"]
edition = "2018"
description = "Converts Markdown to Atlassian markup"
readme = "README.md"
repository = "https://github.com/guppy0130/markrust"
keywords = ["markdown", "atlassian"]
categories = ["command-line-utilities", "template-engine"]
exclude = ["setup_env.ps1"]

[dependencies.pulldown-cmark]
version = "0.8.0"
default-features = false
features = [ "simd" ]

[dependencies.clap]
version = "2.33.3"
default-features = true
features = [ "yaml" ]
