name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.set_release_url.outputs.release_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: cargo fmt -- --check
      - name: Test
        run: cargo test --verbose
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Set release url
        id: set_release_url
        run: echo '::set-output name=release_url::${{ steps.create_release.outputs.upload_url }}'


  build-windows:
    runs-on: windows-latest
    needs: prep
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prep.outputs.release_url }}
          asset_path: ./target/release/markrust.exe
          asset_name: markrust.exe
          asset_content_type: application/octet-stream

  build-linux:
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prep.outputs.release_url }}
          asset_path: ./target/release/markrust
          asset_name: markrust
          asset_content_type: application/octet-stream
